export const colors = {
  oliveDrab: '#7e9b24',
  pistachio: '#86c100',
  pomegranate: '#f44d27',
  tallPoppy: '#bc3b2a',
  cinnabar: '#e2472d',
  osloGray: '#878f93',
  pampas: '#fcfcfa',
  doveGray: '#666666',
  nobel: '#bbb4b3',
  mineShaft: '#333333',
  capeCod: '#3a3d3c',
  mercury: '#e3e3e3',
  gray: '#7f7f7f',
  dustyGray: '#999999',
};

export default {
  main: colors.cinnabar,
  mainBG: colors.capeCod,
  primaryFont: 'Calibri, Helvetica, sans-serif',
  primary: colors.oliveDrab,
  secondary: colors.tallPoppy,
  tertiary: colors.gray,
  primaryHover: colors.pistachio,
  secondaryHover: colors.pomegranate,
  tertiaryHover: colors.dustyGray,
  noneWhite: colors.pampas,
  headerHover: colors.doveGray,
  outlines: colors.nobel,
  text: colors.mineShaft,
  border: colors.mercury,
  simple: colors.gray,
  gutter: 0,
};
