export const GENERATE_PASSWORD = 'GENERATE_PASSWORD';
export const GENERATE_PASSWORD_SUCCESS = 'GENERATE_PASSWORD_SUCCESS';
export const GENERATE_PASSWORD_ERROR = 'GENERATE_PASSWORD_ERROR';
export const CLEAR_PASSWORD = 'CLEAR_PASSWORD';
